### ISSUE TITLE
Link mati

### ISSUE THREAD

**Issue by ZakyHermawan** [hendisantika/List-All-Programming-Telegram-Group#105]
Ga bisa join telegram android id, error message : "Sorry, this chat does not seem to exist"

**Comment by hendisantika** [comment]
Bisa disebutkan grup Android yg mana @ZakyHermawan ?
Soalnya barusan saya cek semuanya bisa diklik.

**Comment by ZakyHermawan** [comment]
**Tentang Telegram**
    TeleGram Android ID

**Comment by hendisantika** [comment]
Ooo... di bagian tentang nya ya. OK. Nanti saya hapus.

**Comment by hendisantika** [comment]
Done. Ya @ZakyHermawan . Sudah saya hapus.
