### ISSUE TITLE
Link for Pentester Indonesia is broken

### ISSUE THREAD

**Issue by panjiahnh** [hendisantika/List-All-Programming-Telegram-Group#107]
Couldn't find Pentester Indonesia group. The link is broken.

**Comment by hendisantika** [comment]
Sebentar, mungkin grupnya diubah settingan jadi private group.

**Comment by hendisantika** [comment]
Adminnya konfirmasi bahwa mereka mengubah kebijakannya dari public groups menjadi private group. Oleh karena itu saya akan remove list nya. Karena yang ada d list harusnya public group.
