### ISSUE TITLE
Groups not found

### ISSUE THREAD

**Issue by Yousha** [hendisantika/List-All-Programming-Telegram-Group#12]
Most of those Telegram groups are Closed/Disbanded...

**Comment by hendisantika** [comment]
Which groups @Yousha ?
Please mention here.
Thanks

**Comment by dikiaap** [comment]
I just checked out @Yousha profile. I think he's an Iraninan guy.
This repository should be add some highlights about indonesian group as I mentioned in [here](https://github.com/hendisantika/List-All-Programming-Telegram-Group/issues/15#issuecomment-313440916).
