### ISSUE TITLE
New Group Add

### ISSUE THREAD

**Issue by recodeking** [hendisantika/List-All-Programming-Telegram-Group#15]
@parrotsecgroup
https://www.parrotsec.org/
https://telegram.me/joinchat/AerigkC4pztMc7Hus7vRZg
Discover the Parrot Universe and get the most from our awesome Debian-based platform.
Professional tools for security testing, software development and privacy defense, all in one place.

**Comment by dikiaap** [comment]
Well, this is actually the right issue.
But this is a list of indonesian groups, your request definitely will not be accepted.
The details of `List-All-Programming-Telegram-Group` and `Awesome Telegram Groups` is very easy to search in google and thus making this as an international group. This thing makes some misunderstanding.
@hendisantika will you change it a bit more to indonesia?
Like `Awesome Indonesia Telegram Groups`.
