### ISSUE TITLE
uixnusantara mati.

### ISSUE THREAD

**Issue by ijash** [hendisantika/List-All-Programming-Telegram-Group#192]
![image](https://user-images.githubusercontent.com/30673286/94825313-350e4100-0430-11eb-8840-e18ab22d7670.png)

**Comment by hendisantika** [comment]
Sekalian send PR untuk fix dead link aja atuhh. Hehehehe

**Comment by ijash** [comment]
@hendisantika sudah di https://github.com/hendisantika/List-All-Programming-Telegram-Group/pull/197
