### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by empeje** [hendisantika/List-All-Programming-Telegram-Group#211]
- Android Developer Medan

**Comment by hendisantika** [comment]
Di-remove aja broken link nya terus send PR ke sini @empeje

**Comment by empeje** [comment]
okeay nanti sekalian ya ada beberapa ya broken @hendisantika

**Comment by empeje** [comment]
Untuk catat: 

C# Indonesia
Laravel Semarang
Serverless tech
