### ISSUE TITLE
Sorry, this group is not accessible

### ISSUE THREAD

**Issue by blessseeker** [hendisantika/List-All-Programming-Telegram-Group#218]
Gak bisa akses Agile Circles Indonesia

![Screenshot_20210125_161323](https://user-images.githubusercontent.com/45768002/105685143-57205780-5f28-11eb-94e3-0a8b59861fc8.png)

**Comment by hendisantika** [comment]
Saya bisa koq --> https://t.me/agilecirclesid

**Comment by hendisantika** [comment]
No response?
Then, I will close this issue.
