### ISSUE TITLE
Found a lot of broken links

### ISSUE THREAD

**Issue by retr00exe** [hendisantika/List-All-Programming-Telegram-Group#222]
I just scrolling and clicking each group in this repo and found a lot of broken links 😕
- [Coderjs](https://t.me/joinchat/GpYOBU7NtL71-XtbwqmCjQ)
- [Trading Bitcoin](https://t.me/noobitcoin)
- [Bengkel KMB](https://t.me/kmbteam)
- [Aceh InfoTech](https://t.me/AcehInfoTech)
- [Lombok Developer Meetup](https://t.me/lombokdevmeetup)
- [W3ID - WWWID PWA](https://t.me/wwwid_pwa)
- [Slackware Indonesia](https://t.me/SlackwareID)
- [Mac OS X ID](https://t.me/MacOSXIDGroup)
- [MIKROTIK INDONESIA](https://t.me/MIKROTIK_INDONESIA)
- [Developer Muda Unity](https://t.me/devmudaunity)

**Comment by hendisantika** [comment]
Can You send PR to remove those broken link?

**Comment by retr00exe** [comment]
Sure, I'll be working on it soon

**Comment by hendisantika** [comment]
Thank You @retr00exe
