### ISSUE TITLE
Nambahin @belajarhtmlcss

### ISSUE THREAD

**Issue by mazipan** [hendisantika/List-All-Programming-Telegram-Group#24]
Sekarang buat Frontend Developer sebenarnya sudah ada @FrontEndId, sayangnya groupnya gak keurus dengan baik sama Admin nya.

Akhirnya om Agil Baka bikin group yang tentang Frontend juga yaitu : @belajarhtmlcss [https://t.me/belajarhtmlcss](https://t.me/belajarhtmlcss)

Bisa request buat nambahin di List nya kang ?
Tapi enaknya masuk grouping yang mana ya ?
Saya juga bingung.
Apa buatin grouping baru HTML/CSS ya ?

**Comment by hendisantika** [comment]
OK, saya tambahkan aja ke grup development aja ya, @mazipan.
