### ISSUE TITLE
Adding hacktoberfest topics

### ISSUE THREAD

**Issue by CakKhoiron** [hendisantika/List-All-Programming-Telegram-Group#243]
Good morning, Mas Hendi.
How about adding hacktoberfest as one of topics for this repo?
In the [latest rules](https://hacktoberfest.digitalocean.com/resources/participation), the repository should add hacktoberfest topics to be counted as hacktoberfest PR.
Maybe can attract some seasonal crowd in this repository.
:)

**Comment by hendisantika** [comment]
Boleh juga.

**Comment by CakKhoiron** [comment]
Mantab.
Makasih banyak, Mas Hendi.
