### ISSUE TITLE
[Proposal] Menambah atau mengubah kategori

### ISSUE THREAD

**Issue by mohzulfikar** [hendisantika/List-All-Programming-Telegram-Group#259]
Terdapat 1 kategori yang ingin saya ajukan, yaitu ***Cloud Infrastructure***. Nantinya, di dalam kategori ini bisa ditambah komunitas yang mendalami tools atau software untuk self-managed (private) cloud.

Contoh salah satu komunitasnya adalah openstack indonesia. Bagaimana menurut Mas @hendisantika ?

**Comment by hendisantika** [comment]
Boleh

**Comment by mohzulfikar** [comment]
Please review #260 Mas @hendisantika . Terima Kasih
