### ISSUE TITLE
Request tambahin telegram group untuk RPA

### ISSUE THREAD

**Issue by kodeindra** [hendisantika/List-All-Programming-Telegram-Group#263]
RPA Indonesia

[Komunitas RPA Indonesia](https://t.me/KomunitasRPAIndonesia)

thanks gan.

**Comment by hendisantika** [comment]
Besok ane Merge PR nya ya. Hari ini jatah commit nya udah habis. #AwAwAw #GakGakGak

**Comment by kodeindra** [comment]
gpp. terima kasih banyak Gan.

**Comment by hendisantika** [comment]
Send PR aja @kodeindra

**Comment by aroyan** [comment]
Yang ini boleh ditambahkan juga, apa nunggu yang open issue open pr bang?

**Comment by hendisantika** [comment]
Send PR aja @aroyan

**Comment by kodeindra** [comment]
thanks kk
