### ISSUE TITLE
Vue.JS Indonesia

### ISSUE THREAD

**Issue by ggalihpp** [hendisantika/List-All-Programming-Telegram-Group#33]
https://t.me/vuejsid

tambahan lagi mungkin, community nya Makers Institute di Bandung, yang kemaren bikin event bareng TIA sama Bandung JS

https://t.me/makerscommunity

**Comment by hendisantika** [comment]
Harusnya Pull Request bukan issue om @ggalihpp

**Comment by ggalihpp** [comment]
ok sorry, will close
