### ISSUE TITLE
Group javascript

### ISSUE THREAD

**Issue by ekaprasasti** [hendisantika/List-All-Programming-Telegram-Group#6]
Halo, apakah sudah ada group telegram untuk komunitas javascript?

**Comment by hendisantika** [comment]
Sedang dipertimbangkan.

**Comment by hendisantika** [comment]
Kalau Javascript khusus sich gak ada. Tapi kalau anak2nya banyak. Hehehehe.

Ada NodeJS, AngularJS, Polimer dll.
Bisa dilihat di list nya gan.
