### ISSUE TITLE
tambah fitur

### ISSUE THREAD

**Issue by daffaalam** [hendisantika/List-All-Programming-Telegram-Group#70]
tambahin fitur `Open Link On New Tab` macam di HTML `target="_blank"`

**Comment by nusendra** [comment]
masalahnya markdown github belum support untuk open in new tab. harus di tulis pake html baru bisa. Kalau perlu diubah ke format html, boleh lah saya PR nanti

@daffaalam @hendisantika

**Comment by SunDi3yansyah** [comment]
gk setuju karena HTML gk enak dibaca :dancer: bener kaya atas klo mau new tab mening pake mouse atau keyboard
